# Generated by Django 6.0.5 on 2026-06-21 02:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0006_remove_property_properties__created_72ecc3_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="cnic",
        ),
        migrations.RemoveField(
            model_name="property",
            name="phone_number",
        ),
    ]
