# Generated by Django 6.0.5 on 2026-06-21 18:56

from django.db import migrations
from django.db.models import F


def preserve_original_timestamps(apps, schema_editor):
    apps.get_model("properties", "Favorite").objects.update(
        created_at=F("favorited_at")
    )
    apps.get_model("properties", "PropertyImage").objects.update(
        created_at=F("uploaded_at")
    )


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0007_remove_property_cnic_remove_property_phone_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="favorite",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="propertyimage",
            options={
                "ordering": ["-is_primary", "created_at"],
                "verbose_name": "Property Image",
                "verbose_name_plural": "Property Images",
            },
        ),
        migrations.RunPython(
            preserve_original_timestamps,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="favorite",
            name="favorited_at",
        ),
        migrations.RemoveField(
            model_name="propertyimage",
            name="uploaded_at",
        ),
    ]
