# Generated by Django 6.0.5 on 2026-06-21 20:41

import apps.properties.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "properties",
            "0008_alter_favorite_options_alter_propertyimage_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="documents",
            field=models.FileField(
                blank=True,
                null=True,
                storage=apps.properties.models.private_document_storage,
                upload_to=apps.properties.models.documents_upload_path,
            ),
        ),
    ]
