# Generated by Django 6.0.5 on 2026-07-01 20:45

import apps.properties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0009_alter_property_documents"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Primary image shown on cards, the map, and as the lead photo. Required to publish.",
                null=True,
                upload_to=apps.properties.models.property_thumbnail_upload_path,
            ),
        ),
    ]
