# Generated by Django 6.0.5 on 2026-07-01 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0011_backfill_property_thumbnail"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="propertyimage",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Property Image",
                "verbose_name_plural": "Property Images",
            },
        ),
        migrations.RemoveConstraint(
            model_name="propertyimage",
            name="one_primary_image_per_property",
        ),
        migrations.RemoveField(
            model_name="propertyimage",
            name="is_primary",
        ),
    ]
